Azure wal
zalando/spilo pull request #514
Opened 2020-11-18 13:20 UTC by ssinger

Add support for sending wal via wal-g to azure storage.
This addresses issue  #383

2020-11-18 14:11 UTC, CyberDem0n reviewed
Hi @ssinger, thank you for the PR,
please fix python formatting issues: https://github.com/zalando/spilo/pull/514/checks?check_run_id=1418286759#step:7:6

2020-11-20 09:42 UTC, carlreid commented on ENVIRONMENT.rst
> +- **AZURE_STORAGE_ACCONT_ACCESS_KEY**:(optional) the access key for the azure storage account used for WAL backups.
There's a typo here:
```suggestion
- **AZURE_STORAGE_ACCOUNT_ACCESS_KEY**:(optional) the access key for the azure storage account used for WAL backups.
```

But I see later in the code the mention of `AZURE_STORAGE_ACCESS_KEY`, so I assume the environment variable should be this instead?

2020-11-23 07:35 UTC, CyberDem0n requested changes
Since currently Azure is not enabled for wal-e it would make sense to automatically set `USE_WALG_BACKUP` to `true` if `WALG_AZ_PREFIX` is defined:

```diff
     if any(placeholders.get(n) for n in AUTO_ENABLE_WALG_RESTORE):
         placeholders.setdefault('USE_WALG_RESTORE', 'true')
+    if placeholders.get('WALG_AZ_PREFIX'):
+        placeholders.setdefault('USE_WALG_BACKUP', 'true')
     set_walg_placeholders(placeholders)
```

2020-11-23 07:35 UTC, CyberDem0n commented on postgres-appliance/scripts/configure_spilo.py
> +                         ('WAL_GS_BUCKET', 'WALE_GS_PREFIX', 'WALG_GS_PREFIX', 'WALG_AZ_PREFIX'))
This change is not required, `AUTO_ENABLE_WALG_RESTORE` already contains `WALG_AZ_PREFIX`.

2020-11-23 07:35 UTC, CyberDem0n commented on postgres-appliance/scripts/configure_spilo.py
> +                                    'WAL_GS_BUCKET', 'WALE_GS_PREFIX', 'WALG_GS_PREFIX', 'WALG_AZ_PREFIX'))
This change is not required, `AUTO_ENABLE_WALG_RESTORE` already contains `WALG_AZ_PREFIX`.

2020-11-23 07:35 UTC, CyberDem0n commented on postgres-appliance/scripts/configure_spilo.py
> +            s3_names + swift_names + gs_names + walg_names + azure_names:
Lets merge these two lines, so it look nicely.
```suggestion
                 'WALG_AZ_PREFIX'] + s3_names + swift_names + gs_names + walg_names + azure_names:
```

2020-11-23 07:35 UTC, CyberDem0n commented on postgres-appliance/scripts/configure_spilo.py
> -
Seems like unrelated change.

2020-11-26 15:37 UTC, FxKu commented
:+1:

2020-11-26 16:03 UTC, CyberDem0n approved these changes

2020-11-26 16:03 UTC, CyberDem0n commented
:+1:

2020-11-26 16:04 UTC, merged

2020-11-26 16:04 UTC, CyberDem0n commented
Merged, thank you @ssinger!