Add SSH_PORT environment vairable for wal-g
zalando/spilo pull request #676
Opened 2021-12-31 06:25 UTC by allen12921

Since user may use no standard ssh port 22 for wal-g backup and restore

2022-01-03 14:49 UTC, CyberDem0n requested changes
Please also update the documentation: https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst#wal-g

2022-01-03 14:49 UTC, CyberDem0n commented on postgres-appliance/scripts/configure_spilo.py
> +WALG_SSH_NAMES = ['WALG_SSH_PREFIX', 'SSH_PRIVATE_KEY_PATH', 'SSH_USERNAME','SSH_PORT']
```suggestion
WALG_SSH_NAMES = ['WALG_SSH_PREFIX', 'SSH_PRIVATE_KEY_PATH', 'SSH_USERNAME', 'SSH_PORT']
```

2022-01-06 08:38 UTC, sdudoladov commented
:+1:

2022-01-06 08:39 UTC, CyberDem0n commented
:+1:

2022-01-06 08:39 UTC, CyberDem0n approved these changes

2022-01-06 08:39 UTC, merged